name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Deploy to EC2
      env:
        EC2_USER: ubuntu
        EC2_HOST: ${{ vars.EC2_HOST }}
        EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "${EC2_KEY}" | base64 -d > key.pem
        chmod 400 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${EC2_HOST} << 'EOF'
          cd /home/ubuntu/goldhouse-production/server
          git pull origin main
          if pm2 list | grep -q "your-app-name"; then
            pm2 restart your-app-name
          else
            pm2 start index.js index
          fi
        EOF